### ISSUE TITLE
vagrant "hello" script fails

### ISSUE THREAD

**Issue by boneskull** [apache/incubator-openwhisk#2538]
I'm going thru the Vagrant installation method (macOS Sierra), and am getting this error, presumably near the end of the script:

```
==> default: ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
==> default: ok: whisk API host set to 192.168.33.13
==> default: ok: whisk namespace set to guest
==> default: ++ wsk action invoke /whisk.system/utils/echo -p message hello --result
==> default: error: Unable to invoke action 'utils/echo': There was an internal server error. (code 52)
==> default: Run 'wsk --help' for usage.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

After this, I ssh into the machine, and execute the above command manually:

```sh
vagrant@vagrant-ubuntu-trusty-64:~$ wsk action invoke /whisk.system/utils/echo -p message hello --result
{
    "message": "hello"
}
```

...which seems like success.  Could be a race condition?

My working copy is at revision d86461524a938fd165fbbba61b43823b1d1ae8af.

**Comment by mateenrehan** [comment]
@boneskull Even my vagrant "hello" script is failing and if I ssh and run the the hello script it is not working.  
` ==> default: 
==> default: TASK [controller : (re)start controller] ***************************************
==> default: Tuesday 01 August 2017  14:11:55 +0000 (0:00:00.352)       0:02:19.848 ******** 
==> default: changed: [172.17.0.1]
==> default: 
==> default: TASK [controller : wait until the Controller in this host is up and running] ***
==> default: Tuesday 01 August 2017  14:13:12 +0000 (0:01:16.650)       0:03:36.498 ******** 
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (12 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (11 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (10 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (9 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (8 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (7 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (6 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (5 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (4 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (3 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (2 retries left).
==> default: FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
==> default: fatal: [172.17.0.1]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}
==> default: 
==> default: PLAY RECAP *********************************************************************
==> default: 172.17.0.1                 : ok=13   changed=11   unreachable=0    failed=1   
==> default: Tuesday 01 August 2017  14:14:16 +0000 (0:01:04.416)       0:04:40.915 ******** 
==> default: =============================================================================== 
==> default: kafka : pull the ches/kafka:0.10.2.1 image ----------------------------- 87.45s
==> default: controller : (re)start controller -------------------------------------- 76.65s
==> default: controller : wait until the Controller in this host is up and running -- 64.42s
==> default: kafka : pull the zookeeper:3.4 image ----------------------------------- 24.58s
==> default: kafka : wait until the Zookeeper in this host is up and running --------- 7.48s
==> default: kafka : wait until the kafka server started up -------------------------- 5.45s
==> default: kafka : create the health topic ----------------------------------------- 3.24s
==> default: kafka : create the invoker topics --------------------------------------- 2.53s
==> default: kafka : create the active-ack topics ------------------------------------ 2.49s
==> default: Gathering Facts --------------------------------------------------------- 2.44s
==> default: Gathering Facts --------------------------------------------------------- 2.23s
==> default: kafka : (re)start zookeeper --------------------------------------------- 0.73s
==> default: kafka : (re)start kafka ------------------------------------------------- 0.68s
==> default: controller : ensure controller log directory is created with permissions --- 0.35s
==> default: kafka : remove zookeeper ------------------------------------------------ 0.04s
==> default: controller : docker login ----------------------------------------------- 0.04s
==> default: kafka : remove kafka ---------------------------------------------------- 0.03s
==> default: controller : pull the latest image of controller ------------------------ 0.03s
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by mateenrehan** [comment]
My vagrant script is working now. Thanks.

**Comment by reiz** [comment]
@boneskull @mateenrehan For the `./hello` is failing with: 

```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

If I ssh into the box I can see that not all Docker containers are running. The controller containers are in exited status and the whole thing is not working. 

The strange thing is that building the Vagrant box worked already yesterday. Everything was up and running and I could play with the API. But now all suddenly building the box doesn't work anymore. 

Any suggestions how to fix this?

**Comment by reiz** [comment]
I tried now a couple things to solve this. Fore example editing the `/etc/sudoers` file like described in this [thread](https://github.com/hashicorp/vagrant/issues/1659), but that didn't solve the problem. I further destroyed the whole Vagrant box and even deleted the `.vagrant` directory and started again `.hello`. But still getting this error message: 

```
default: TASK [controller : wait until the Controller in this host is up and running] ***
    default: Friday 10 November 2017  10:11:09 +0000 (0:01:27.343)       0:03:57.068 *******
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (12 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (12 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (11 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (11 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (10 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (10 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (9 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (9 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (8 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (8 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (7 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (7 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (6 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (6 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (5 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (5 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (4 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (4 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (3 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (3 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (2 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (2 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
    default: fatal: [controller1]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10002/ping"}
    default: fatal: [controller0]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}
    default:
    default: PLAY RECAP *********************************************************************
    default: 172.17.0.1                 : ok=10   changed=9    unreachable=0    failed=0
    default: controller0                : ok=10   changed=2    unreachable=0    failed=1
    default: controller1                : ok=10   changed=2    unreachable=0    failed=1
    default: Friday 10 November 2017  10:12:14 +0000 (0:01:04.302)       0:05:01.370 *******
    default: ===============================================================================
    default: kafka : pull the ches/kafka:0.10.2.1 image ----------------------------- 91.63s
    default: controller : (re)start controller -------------------------------------- 87.34s
    default: controller : wait until the Controller in this host is up and running -- 64.30s
    default: kafka : pull the zookeeper:3.4 image ----------------------------------- 25.54s
    default: kafka : wait until the Zookeeper in this host is up and running --------- 7.31s
    default: kafka : wait until the kafka server started up -------------------------- 5.40s
    default: kafka : create the active-ack topics ------------------------------------ 4.24s
    default: kafka : create the health and the cacheInvalidation topic --------------- 4.21s
    default: kafka : create the invoker topics --------------------------------------- 4.00s
    default: Gathering Facts --------------------------------------------------------- 2.15s
    default: Gathering Facts --------------------------------------------------------- 2.06s
    default: kafka : (re)start zookeeper --------------------------------------------- 0.70s
    default: kafka : (re)start kafka ------------------------------------------------- 0.59s
    default: controller : check if whisk_local_whisks with CouchDB exists ------------ 0.41s
    default: controller : create seed nodes list ------------------------------------- 0.32s
    default: controller : ensure controller log directory is created with permissions --- 0.29s
    default: controller : check if whisk_local_subjects with CouchDB exists ---------- 0.27s
    default: controller : check if whisk_local_activations with CouchDB exists ------- 0.26s
    default: controller : check, that required databases exist ----------------------- 0.18s
    default: controller : docker login ----------------------------------------------- 0.04s
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Feedback is welcome.
