### ISSUE TITLE
Vagrant provisioning results in SSLV3_ALERT_BAD_CERTIFICATE and failure to ping https://172.17.0.1:10001/ping

### ISSUE THREAD

**Issue by develpr** [apache/incubator-openwhisk#3431]
## Environment details:

*Vagrant install quick start method used*

Host: macOS High Sierra
Vagrant: 2.0.2
VirtualBox: 5.2.8

## Steps to reproduce the issue:

1.   clone `https://github.com/apache/incubator-openwhisk`
2.  cd `<root of cloned repo>/tools/vagrant`
3.  `./hello`

*NOTE: as noted below, I had issues with the base box and the `vagrant` user not being available / created with the base box used.* I got around this by adding just replacing `su vagrant` with `sudo su` to the provisioning script in the `Vagrantfile`. **Still, it's important to point this out because I realize this could be the ultimate root cause of my issue so please note!**

## Provide the expected results and outputs:

I expected the results outlined in the readme / quick start

## Provide the actual results and outputs:

There seems to be a failure, I think connecting to CouchDB. Console output:

```

... snip snip snip...


 default: 
    default: TASK [controller : create seed nodes list] *************************************
    default: Tuesday 13 March 2018  14:44:39 +0000 (0:00:00.200)       0:01:13.806 ********* 
    default: ok: [controller0] => (item=(0, u'172.17.0.1'))
    default: 
    default: TASK [controller : (re)start controller] ***************************************
    default: Tuesday 13 March 2018  14:44:39 +0000 (0:00:00.224)       0:01:14.030 ********* 
    default: changed: [controller0]
    default: 
    default: TASK [controller : wait until the Controller in this host is up and running] ***
    default: Tuesday 13 March 2018  14:44:41 +0000 (0:00:01.350)       0:01:15.381 ********* 
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (12 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (11 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (10 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (9 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (8 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (7 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (6 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (5 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (4 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (3 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (2 retries left).
    default: FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
    default: fatal: [controller0]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:590)>", "redirected": false, "status": -1, "url": "https://172.17.0.1:10001/ping"}
    default: 
    default: Status code was not [200]: Request failed: <urlopen error [SSL:
    default: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:590)>
    default: 
    default: PLAY RECAP *********************************************************************
    default: controller0                : ok=20   changed=7    unreachable=0    failed=1   
    default: kafka0                     : ok=12   changed=7    unreachable=0    failed=0   
    default: Tuesday 13 March 2018  14:45:44 +0000 (0:01:03.162)       0:02:18.544 ********* 
    default: =============================================================================== 
    default: controller : wait until the Controller in this host is up and running -- 63.16s
    default: zookeeper : pull the zookeeper:3.4 image ------------------------------- 32.15s
    default: kafka : pull the wurstmeister/kafka:0.11.0.1 image --------------------- 20.30s
    default: zookeeper : wait until the Zookeeper in this host is up and running ----- 7.31s
    default: kafka : wait until the kafka server started up -------------------------- 5.50s
    default: controller : (re)start controller --------------------------------------- 1.35s
    default: controller : copy certificates ------------------------------------------ 1.09s
    default: controller : copy jmxremote password file ------------------------------- 0.73s
    default: zookeeper : (re)start zookeeper ----------------------------------------- 0.70s
    default: controller : copy nginx certificate keystore ---------------------------- 0.66s
    default: kafka : (re)start kafka ------------------------------------------------- 0.63s
    default: Gathering Facts --------------------------------------------------------- 0.51s
    default: controller : copy jmxremote access file --------------------------------- 0.51s
    default: Gathering Facts --------------------------------------------------------- 0.46s
    default: controller : check if whisk_local_whisks with CouchDB exists ------------ 0.41s
    default: controller : ensure controller config directory is created with permissions --- 0.35s
    default: Gathering Facts --------------------------------------------------------- 0.33s
    default: kafka : create kafka certificate directory ------------------------------ 0.25s
    default: controller : check if whisk_local_subjects with CouchDB exists ---------- 0.24s
    default: controller : check if whisk_local_activations with CouchDB exists ------- 0.24s

... snip snip snip...

```

## Additional information you deem important:

* I also tried this on a machine with a slightly older version of vagrant (1.9.3) and VirtualBox (5.1.8), same results
* I had issues with the base box and the `vagrant` user not being available / created. I got around this by adding `sudo su` in place of `su vagrant` to run everything with open permissions, same result
