### ISSUE TITLE
Vagrant Hello Not Starting on Mac

### ISSUE THREAD

**Issue by klcodanr** [apache/incubator-openwhisk#3540]
## Environment details:

* vagrant on Mac

## Steps to reproduce the issue:

1.   Follow the directions on the Vagrant Quick Start: https://github.com/apache/incubator-openwhisk#quick-start

## Provide the expected results and outputs:

The expected result is what is described in the quickstart

## Provide the actual results and outputs:

The hello command fails to complete and exits with the following exception:

```
default: TASK [check if whisk_local_subjects with CouchDB exists] ***********************
    default: Wednesday 11 April 2018  12:44:27 +0000 (0:00:00.090)       0:00:00.860 ******* 
    default: fatal: [ansible]: FAILED! => {"changed": false, "content": "", "msg": "Status code was not [200, 404]: Request failed: <urlopen error timed out>", "redirected": false, "status": -1, "url": "http://192.168.99.100:5984/whisk_local_subjects"}
    default: 
    default: Status code was not [200, 404]: Request failed: <urlopen error timed out>
    default: 
    default: PLAY RECAP *********************************************************************
    default: ansible                    : ok=3    changed=0    unreachable=0    failed=1   
    default: Wednesday 11 April 2018  12:44:58 +0000 (0:00:30.360)       0:00:31.221 ******* 
    default: =============================================================================== 
    default: check if whisk_local_subjects with CouchDB exists ---------------------- 30.36s
    default: Gathering Facts --------------------------------------------------------- 0.57s
    default: include_tasks ----------------------------------------------------------- 0.09s
    default: include_tasks ----------------------------------------------------------- 0.09s

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong
```

Full log: https://gist.github.com/klcodanr/a5b02240091deefe09b33f9f75d0dfe4

## Additional information you deem important:

*OS Version*
 ``` 
    System Version: macOS 10.13.4 (17E199)
      Kernel Version: Darwin 17.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

*Vagrant Version*
```
Vagrant 2.0.3
```

*VirtualBox Version*
```
5.2.8 r121009 (Qt5.6.3)
```
