### ISSUE TITLE
where is goPrepare gradle task?

### ISSUE THREAD

**Issue by norricorp** [apache/incubator-openwhisk#3649]
## Environment details:
Windows 10

## Steps to reproduce the issue:

$ git clone https://github.com/openwhisk/openwhisk.git
$ cd openwhisk/tools/vagrant
$ ./hello
## Provide the expected results and outputs:
This fails
output comes here
==> default: :goPrepare
==> default:
==> default: FAILED
==> default: FAILURE:
==> default: Build failed with an exception.
==> default: * What went wrong:
==> default:
==> default: Execution failed for task ':goPrepare'.
==> default: >
==> default: Create symbolic link at /home/vagrant/openwhisk/bin/openwhisk-cli/.gogradle/project_gopath/src/github.com/apache/incubator-openwhisk-cli failed

I can not find the goPrepare task. Where is it? Have asked on stackoverflow and no reply.

**Comment by dubee** [comment]
@csantanapr, from the above output it looks like Vagrant clones the CLI repo and tries to build the CLI source. Not sure why that is necessary?

**Comment by norricorp** [comment]
but should it be calling goPrepare task? I am making the wild guess that it prepares the golang that is downloaded earlier.
I have got the full log if anyone wants that.

**Comment by dubee** [comment]
@csantanapr, should be `su vagrant -c './gradlew compile'`. `releaseBinaries` is what Travis uses to publish the CLI on the Releases page. 

Just wondering why Vagrant needs to build the CLI  at all instead of just download it from the Releases page.

**Comment by dubee** [comment]
@csantanapr, @norricorp, is Go installed in Vagrant?

**Comment by dubee** [comment]
@mdeuser, FYI.

**Comment by csantanapr** [comment]
I just tried and it worked for me on OSX.
From the error message I think is problem trying to create soft links under Windows filesystem from inside the Vagrant/Linux VM

```
Create symbolic link at...
```

Here is the output from mine running on OSX
```
default: ++ cd /home/vagrant/openwhisk/bin
    default: ++ rm -rf openwhisk-cli
    default: ++ su vagrant -c 'git clone --depth=1 https://github.com/apache/incubator-openwhisk-cli.git openwhisk-cli'
    default: Cloning into 'openwhisk-cli'...
    default: ++ cd openwhisk-cli
    default: ++ su vagrant -c './gradlew releaseBinaries'
    default: Download https://plugins.gradle.org/m2/gradle/plugin/com/github/blindpirate/gogradle/0.8.1/gogradle-0.8.1.pom
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr4/4.6/antlr4-4.6.pom
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.pom
    default:
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.pom
    default: Download https://plugins.gradle.org/m2/com/google/inject/guice/4.1.0/guice-4.1.0.pom
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr4-master/4.6/antlr4-master-4.6.pom
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/41/commons-parent-41.pom
    default:
    default: Download https://plugins.gradle.org/m2/com/google/inject/guice-parent/4.1.0/guice-parent-4.1.0.pom
    default:
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/38/commons-parent-38.pom
    default: Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
    default: Download https://plugins.gradle.org/m2/com/google/google/5/google-5.pom
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/35/commons-parent-35.pom
    default:
    default: Download https://plugins.gradle.org/m2/commons-io/commons-io/2.5/commons-io-2.5.pom
    default: Download https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom
    default: Download https://plugins.gradle.org/m2/org/apache/apache/15/apache-15.pom
    default:
    default: Download https://plugins.gradle.org/m2/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/core/jackson-databind/2.8.5/jackson-databind-2.8.5.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/core/jackson-annotations/2.8.5/jackson-annotations-2.8.5.pom
    default: Download https://plugins.gradle.org/m2/com/google/code/findbugs/annotations/3.0.1/annotations-3.0.1.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.8.5/jackson-dataformat-yaml-2.8.5.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/oss-parent/27/oss-parent-27.pom
    default: Download https://plugins.gradle.org/m2/net/lingala/zip4j/zip4j/1.3.2/zip4j-1.3.2.pom
    default: Download https://plugins.gradle.org/m2/com/typesafe/sbt/sbt-interface/0.13.13/sbt-interface-0.13.13.pom
    default: Download https://plugins.gradle.org/m2/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.pom
    default: Download https://plugins.gradle.org/m2/org/apache/ant/ant/1.10.0/ant-1.10.0.pom
    default:
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.6.3/jackson-dataformat-xml-2.6.3.pom
    default: Download https://plugins.gradle.org/m2/org/jooq/joor/0.9.6/joor-0.9.6.pom
    default: Download https://plugins.gradle.org/m2/com/moandjiezana/toml/toml4j/0.7.2/toml4j-0.7.2.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/jackson-parent/2.6.1/jackson-parent-2.6.1.pom
    default: Download https://plugins.gradle.org/m2/org/apache/ant/ant-parent/1.10.0/ant-parent-1.10.0.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/oss-parent/23/oss-parent-23.pom
    default: Download https://plugins.gradle.org/m2/org/antlr/ST4/4.0.8/ST4-4.0.8.pom
    default:
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.pom
    default: Download https://plugins.gradle.org/m2/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.pom
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr4-runtime/4.6/antlr4-runtime-4.6.pom
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr-master/3.5.2/antlr-master-3.5.2.pom
    default:
    default: Download https://plugins.gradle.org/m2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.pom
    default: Download https://plugins.gradle.org/m2/org/glassfish/json/1.0.4/json-1.0.4.pom
    default: Download https://plugins.gradle.org/m2/net/java/jvnet-parent/3/jvnet-parent-3.pom
    default: Download https://plugins.gradle.org/m2/javax/inject/javax.inject/1/javax.inject-1.pom
    default: Download https://plugins.gradle.org/m2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/core/jackson-core/2.8.5/jackson-core-2.8.5.pom
    default: Download https://plugins.gradle.org/m2/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.pom
    default: Download https://plugins.gradle.org/m2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.pom
    default: Download https://plugins.gradle.org/m2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom
    default: Download https://plugins.gradle.org/m2/org/apache/ant/ant-launcher/1.10.0/ant-launcher-1.10.0.pom
    default: Download https://plugins.gradle.org/m2/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.pom
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.6.3/jackson-module-jaxb-annotations-2.6.3.pom
    default: Download https://plugins.gradle.org/m2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.pom
    default: Download https://plugins.gradle.org/m2/com/google/code/gson/gson/2.8.1/gson-2.8.1.pom
    default: Download https://plugins.gradle.org/m2/com/google/code/gson/gson-parent/2.8.1/gson-parent-2.8.1.pom
    default: Download https://plugins.gradle.org/m2/gradle/plugin/com/github/blindpirate/gogradle/0.8.1/gogradle-0.8.1.jar
    default: Download https://plugins.gradle.org/m2/com/google/inject/guice/4.1.0/guice-4.1.0.jar
    default:
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
    default: Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
    default:
    default: Download https://plugins.gradle.org/m2/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr4/4.6/antlr4-4.6.jar
    default:
    default: Download https://plugins.gradle.org/m2/commons-io/commons-io/2.5/commons-io-2.5.jar
    default: Download https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar
    default: Download https://plugins.gradle.org/m2/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar
    default:
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.6.3/jackson-module-jaxb-annotations-2.6.3.jar
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/core/jackson-annotations/2.8.5/jackson-annotations-2.8.5.jar
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.6.3/jackson-dataformat-xml-2.6.3.jar
    default:
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/core/jackson-databind/2.8.5/jackson-databind-2.8.5.jar
    default:
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.8.5/jackson-dataformat-yaml-2.8.5.jar
    default: Download https://plugins.gradle.org/m2/com/google/code/findbugs/annotations/3.0.1/annotations-3.0.1.jar
    default: Download https://plugins.gradle.org/m2/net/lingala/zip4j/zip4j/1.3.2/zip4j-1.3.2.jar
    default: Download https://plugins.gradle.org/m2/com/typesafe/sbt/sbt-interface/0.13.13/sbt-interface-0.13.13.jar
    default: Download https://plugins.gradle.org/m2/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar
    default:
    default: Download https://plugins.gradle.org/m2/org/jooq/joor/0.9.6/joor-0.9.6.jar
    default: Download https://plugins.gradle.org/m2/com/moandjiezana/toml/toml4j/0.7.2/toml4j-0.7.2.jar
    default: Download https://plugins.gradle.org/m2/org/antlr/ST4/4.0.8/ST4-4.0.8.jar
    default: Download https://plugins.gradle.org/m2/org/apache/ant/ant/1.10.0/ant-1.10.0.jar
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
    default: Download https://plugins.gradle.org/m2/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar
    default: Download https://plugins.gradle.org/m2/org/antlr/antlr4-runtime/4.6/antlr4-runtime-4.6.jar
    default:
    default: Download https://plugins.gradle.org/m2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar
    default: Download https://plugins.gradle.org/m2/javax/inject/javax.inject/1/javax.inject-1.jar
    default: Download https://plugins.gradle.org/m2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
    default: Download https://plugins.gradle.org/m2/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar
    default:
    default: Download https://plugins.gradle.org/m2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar
    default: Download https://plugins.gradle.org/m2/com/fasterxml/jackson/core/jackson-core/2.8.5/jackson-core-2.8.5.jar
    default: Download https://plugins.gradle.org/m2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
    default:
    default: Download https://plugins.gradle.org/m2/org/apache/ant/ant-launcher/1.10.0/ant-launcher-1.10.0.jar
    default: Download https://plugins.gradle.org/m2/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
    default:
    default: Download https://plugins.gradle.org/m2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
    default: Download https://plugins.gradle.org/m2/com/google/code/gson/gson/2.8.1/gson-2.8.1.jar
    default: Start downloading go 1.9.4.
    default: downloading https://storage.googleapis.com/golang/go1.9.4.linux-amd64.tar.gz -> /home/vagrant/.gradle/go/binary/go1.9.4.linux-amd64.tar.gz
    default: Extracting /home/vagrant/.gradle/go/binary/go1.9.4.linux-amd64.tar.gz to /home/vagrant/.gradle/go/binary/1.9.4
    default: :index
    default:
    default: :goPrepare
    default:
    default: Use project GOPATH: /home/vagrant/openwhisk/bin/openwhisk-cli/.gogradle/project_gopath
    default: :getGoI18n
    default:
    default: :goI18n
    default: :resolveBuildDependencies
    default:
    default: Resolving github.com/apache/incubator-openwhisk-client-go: commit='e452b524cd745f71c913c5acccf72a8daba6dc71', urls=[https://github.com/apache/incubator-openwhisk-client-go.git, git@github.com:apache/incubator-openwhisk-client-go.git]
    default: Resolving github.com/cloudfoundry/jibber_jabber: commit='bcc4c8345a21301bf47c032ff42dd1aae2fe3027', urls=[https://github.com/cloudfoundry/jibber_jabber.git, git@github.com:cloudfoundry/jibber_jabber.git]
    default: Resolving github.com/fatih/color: commit='87d4004f2ab62d0d255e0a38f1680aa534549fe3', urls=[https://github.com/fatih/color.git, git@github.com:fatih/color.git]
    default: Resolving github.com/ghodss/yaml: commit='0ca9ea5df5451ffdf184b4428c902747c2c11cd7', urls=[https://github.com/ghodss/yaml.git, git@github.com:ghodss/yaml.git]
    default: Resolving github.com/google/go-querystring: commit='9235644dd9e52eeae6fa48efd539fdc351a0af53', urls=[https://github.com/google/go-querystring.git, git@github.com:google/go-querystring.git]
    default: Resolving github.com/hokaccha/go-prettyjson: commit='f75235bd99dad4e98ff360db8372d5c0ef1d054a', urls=[https://github.com/hokaccha/go-prettyjson.git, git@github.com:hokaccha/go-prettyjson.git]
    default: Resolving github.com/inconshreveable/mousetrap: commit='76626ae9c91c4f2a10f34cad8ce83ea42c93bb75', urls=[https://github.com/inconshreveable/mousetrap.git, git@github.com:inconshreveable/mousetrap.git]
    default: Resolving github.com/mattn/go-colorable: commit='d228849504861217f796da67fae4f6e347643f15', urls=[https://github.com/mattn/go-colorable.git, git@github.com:mattn/go-colorable.git]
    default: Resolving github.com/mattn/go-isatty: commit='66b8e73f3f5cda9f96b69efd03dd3d7fc4a5cdb8', urls=[https://github.com/mattn/go-isatty.git, git@github.com:mattn/go-isatty.git]
    default: Resolving github.com/mitchellh/go-homedir: commit='1111e456ffea841564ac0fa5f69c26ef44dafec9', urls=[https://github.com/mitchellh/go-homedir.git, git@github.com:mitchellh/go-homedir.git]
    default: Resolving github.com/nicksnyder/go-i18n: commit='37e5c2de3e03e4b82693e3fcb4a6aa2cc4eb07e3', urls=[https://github.com/nicksnyder/go-i18n.git, git@github.com:nicksnyder/go-i18n.git]
    default: Resolving github.com/spf13/cobra: commit='1238ba19d24b0b9ceee2094e1cb31947d45c3e86', urls=[https://github.com/spf13/cobra.git, git@github.com:spf13/cobra.git]
    default: Resolving github.com/spf13/pflag: commit='367864438f1b1a3c7db4da06a2f55b144e6784e0', urls=[https://github.com/spf13/pflag.git, git@github.com:spf13/pflag.git]
    default: Resolving golang.org/x/sys: commit='7f918dd405547ecb864d14a8ecbbfe205b5f930f', urls=[https://go.googlesource.com/sys]
    default: Resolving gopkg.in/yaml.v2: commit='cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b', urls=[https://gopkg.in/yaml.v2]
    default: :installDependencies
    default: :buildDarwin386
    default:
    default: :buildDarwinAmd64
    default:
    default: :buildLinux386
    default: :buildLinuxAmd64
    default:
    default: :buildLinuxArm
    default:
    default: :buildLinuxArm64
    default:
    default: :buildLinuxPpc64le
    default:
    default: :buildLinuxS390x
    default:
    default: :buildWindows386
    default:
    default: :buildWindowsAmd64
    default:
    default: :goBuild
    default: :compile
    default: :releaseDarwin386
    default: :releaseDarwinAmd64
    default: :releaseLinux386
    default:
    default: :releaseLinuxAmd64
    default:
    default: :releaseLinuxArm
    default: :releaseLinuxArm64
    default: :releaseLinuxPpc64le
    default: :releaseLinuxS390x
    default: :releaseWindows386
    default:
    default: :releaseWindowsAmd64
    default: :individualArchives
    default: :releaseBinaries
    default:
    default: BUILD SUCCESSFUL in 2m 30s
    default: 29 actionable tasks: 29 executed
    default: +++ date
    default: ++ echo 'Mon May 14 19:28:44 UTC 2018: build-cli-end'
```
