### ISSUE TITLE
Apache incubator release 0.9.0, missing application.conf.j2

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk#3815]
As the first time release under Apache as an incubator project, openwhisk does not package the directory tests, which leads to missing of application.conf.j2 during openwhisk installation with ansible script.

There is PR to resolve it: https://github.com/apache/incubator-openwhisk/pull/3803.

You can also bypass this issue by commenting out the following lines in ansible/tasks/writeWhiskProperties.yml:
```
- name: write test's application conf overrides
  template:
          src: "{{ openwhisk_home }}/tests/src/test/resources/application.conf.j2"
         dest: "{{ openwhisk_home }}/tests/src/test/resources/application.conf"
```
