### ISSUE TITLE
Issue with vagrant build

### ISSUE THREAD

**Issue by zak93kost** [apache/incubator-openwhisk#3937]
I am trying to build openwhisk with vagrant and I am receiving the following issue. 

  ```
  default: > Task `:commxzon:scala:compileScala`
    default: Pruning sources from previous analysis, due to incompatible CompileSetup.
    default:
    default: > Task :common:scala:compileScala FAILED
    default:
    default: FAILURE:
    default: Build failed with an exception.
    default: 3 actionable tasks: 3 executed
    default: * What went wrong:
    default: Execution failed for task ':common:scala:compileScala'.
    default: > Java heap space
    default:
    default: * Try:
    default: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    default:
    default: * Get more help at https://help.gradle.org
    default:
    default: BUILD FAILED in 5m 8s
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.


```
Any suggestions?
