### ISSUE TITLE
update swagger for action put

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#4201]
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openwhisk/openwhisk/master/core/controller/src/main/resources/apiv1swagger.json#/Actions/updateAction

define the PUT request for an action to contain now removed fields `binary` and `init`.

**Comment by larandersson** [comment]
As far as I can see, those attributes are already present in the model. The *ActionExec* object contains the following attribute declarations:
```
      init:
        type: string
        description: optional zipfile reference when code kind is 'nodejs'
      binary:
        type: boolean
        description: Whether the action has a binary attachment or not
```
Did you mean that these attributes should be *removed*?
